schema-version: v1
kind: action
metadata:
  name: stakspot-github-create-repository
  display-name: Stackspot Create GitHub Repository
  description: Action to create github repository
  version: 1.0.0
spec:
  type: python
  about: docs/about.md
  usage: docs/usage.md
  release-notes: docs/release-notes.md
  implementation: docs/implementation.md
  inputs:
    - label: Visibility
      name: visibility
      type: text
      required: true
      items: 
        - public
        - internal
        - private
    - label: Client Id
      name: client_id
      type: text
      help: This value will be set as repository secret
    - label: Client Key
      name: client_key
      type: password
      help: This value will be set as repository secret
    - label: Client Realm
      name: client_realm
      type: text
      help: This value will be set as repository secret
  python:
    workdir: .
    script: script.py
